from cs1graphics import*
paper = Canvas( )
head = Circle(75, Point(100,100))
head.setFillColor('yellow')
head.setDepth(60)
paper.add(head)
mouth = Circle(40, Point(100,110))
mouth.setFillColor('black')
mouth.setBorderWidth(0)
mouth.setDepth(52)
paper.add(mouth)
mouthCover = Circle(40, Point(100,100))
mouthCover.setFillColor('yellow')
mouthCover.setBorderWidth(0)
mouthCover.setDepth(51)
paper.add(mouthCover)
